name: .NET Build and Release

on:
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]      # triggers release job on version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      # Only publish when building a tag (for release)
      - name: Publish self-contained .exe
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet publish -c Release -r win-x64 UnityAssetBundlePatcher/UnityAssetBundlePatcher.csproj --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Upload .exe as artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: my-app-exe
          path: ./publish/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: unity-asset-bundle-patcher
          path: ./publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
